-- ■ 오늘도잘수없겠조(5조) 중간보고 ■

--상품별 분석팀
---- 팀장: 꼬북좌
------ 팀원: 마경수

SELECT * FROM PRODCL2;
--● 시간이 부족해 의미있는 인사이트 도출은 어려웠음
--● 추가 작업이 필요하고, 진행중임

--고객별 분석팀
---- 팀장: 조남현
------ 팀원: 이재호, 김태형
SELECT * FROM CUSTDEMO;

--●성별 (무의미)
CREATE TABLE PUR_GENDER AS SELECT 성별,
COUNT(CASE WHEN YEAR=2014 THEN CUSTDEMO.고객번호 END) "14년구매건수", 
COUNT(CASE WHEN YEAR=2015 THEN CUSTDEMO.고객번호 END) "15년구매건수",
SUM(CASE WHEN year=2014 THEN 구매금액 END) "14년구매총액",
SUM(CASE WHEN year=2015 THEN 구매금액 END) "15년구매총액" FROM PURPROD
LEFT OUTER JOIN CUSTDEMO ON PURPROD.고객번호 = CUSTDEMO.고객번호
GROUP BY 성별;

SELECT * FROM PUR_GENDER;
SELECT * FROM PUR_GENDER where "14년구매총액" > "15년구매총액";

--●연령대
CREATE TABLE PUR_AGE AS SELECT 연령대,
COUNT(CASE WHEN YEAR=2014 THEN CUSTDEMO.고객번호 END) "14년구매건수", 
COUNT(CASE WHEN YEAR=2015 THEN CUSTDEMO.고객번호 END) "15년구매건수",
SUM(CASE WHEN year=2014 THEN 구매금액 END) "14년구매총액",
SUM(CASE WHEN year=2015 THEN 구매금액 END) "15년구매총액" FROM PURPROD
LEFT OUTER JOIN CUSTDEMO ON PURPROD.고객번호 = CUSTDEMO.고객번호
GROUP BY 연령대;

SELECT * FROM PUR_AGE;
SELECT * FROM PUR_AGE where "14년구매총액" > "15년구매총액";

--●지역별
CREATE TABLE PUR_AREA AS SELECT 거주지역,
COUNT(CASE WHEN YEAR=2014 THEN CUSTDEMO.고객번호 END) "14년구매건수", 
COUNT(CASE WHEN YEAR=2015 THEN CUSTDEMO.고객번호 END) "15년구매건수",
SUM(CASE WHEN year=2014 THEN 구매금액 END) "14년구매총액",
SUM(CASE WHEN year=2015 THEN 구매금액 END) "15년구매총액" FROM PURPROD
LEFT OUTER JOIN CUSTDEMO ON PURPROD.고객번호 = CUSTDEMO.고객번호
GROUP BY 거주지역
ORDER BY 거주지역;

SELECT * FROM PUR_AREA;
SELECT * FROM PUR_AREA where "14년구매총액" > "15년구매총액";

--●월별
CREATE TABLE PUR_MONTH AS SELECT MONTH,
COUNT(CASE WHEN YEAR=2014 THEN 구매금액 END) "PN2014",
COUNT(CASE WHEN YEAR=2015 THEN 구매금액 END) "PN2015",
SUM(CASE WHEN YEAR=2014 THEN 구매금액 END) "PP2014",
SUM(CASE WHEN YEAR=2015 THEN 구매금액 END) "PP2015"
FROM PURPROD GROUP BY MONTH ORDER BY MONTH;
commit;

SELECT * FROM PUR_MONTH;